# auto_apply_app/infrastructures/agent/stage_codes.py
from enum import Enum


class StageCode(str, Enum):
    # --- Worker stages ---
    INITIALIZING_BROWSER = "INITIALIZING_BROWSER"
    NAVIGATING = "NAVIGATING"
    AUTHENTICATING = "AUTHENTICATING"
    SEARCHING = "SEARCHING"
    EXTRACTING_DATA = "EXTRACTING_DATA"
    SUBMITTING = "SUBMITTING"
    CLEANING_UP = "CLEANING_UP"

    # --- Master stages ---
    LAUNCHING_WORKERS = "LAUNCHING_WORKERS"
    GENERATING_LETTERS = "GENERATING_LETTERS"
    DISPATCHING = "DISPATCHING"
    WAITING_REVIEW = "WAITING_REVIEW"
    LAUNCHING_SUBMISSION = "LAUNCHING_SUBMISSION"
    SAVING_RESULTS = "SAVING_RESULTS"

    # --- Terminal states ---
    COMPLETE = "COMPLETE"
    STOPPED = "STOPPED"
    FAILED = "FAILED"
    NO_JOBS = "NO_JOBS"
