"""initial_schema_sync

Revision ID: 31c54c62cbb0
Revises: 
Create Date: 2026-03-15 07:05:04.831296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31c54c62cbb0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('firstname', sa.String(length=100), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('resume_path', sa.String(length=500), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('current_position', sa.String(length=200), nullable=True),
    sa.Column('current_company', sa.String(length=200), nullable=True),
    sa.Column('school_type', sa.String(length=100), nullable=True),
    sa.Column('graduation_year', sa.String(length=10), nullable=True),
    sa.Column('major', sa.String(length=200), nullable=True),
    sa.Column('study_level', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('auth_users',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_auth_users_email'), 'auth_users', ['email'], unique=True)
    op.create_table('board_credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('job_board', sa.String(length=50), nullable=False),
    sa.Column('login_encrypted', sa.Text(), nullable=True),
    sa.Column('password_encrypted', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_board_credentials_job_board'), 'board_credentials', ['job_board'], unique=False)
    op.create_index(op.f('ix_board_credentials_user_id'), 'board_credentials', ['user_id'], unique=False)
    op.create_table('job_searches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('job_title', sa.String(length=200), nullable=False),
    sa.Column('job_boards', postgresql.ARRAY(sa.Enum('WTTJ', 'HELLOWORK', 'APEC', name='jobboard', native_enum=False)), nullable=False),
    sa.Column('search_status', sa.Enum('PENDING', 'SEARCHING', 'PAUSED', 'COMPLETED', 'CANCELLED', 'FAILED', name='searchstatus', native_enum=False), nullable=False),
    sa.Column('contract_types', postgresql.ARRAY(sa.Enum('INTERNSHIP', 'APPRENTICESHIP', 'FREELANCE', 'TEMPORARY', 'FULL_TIME', name='contracttype', native_enum=False)), nullable=True),
    sa.Column('min_salary', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_searches_user_id'), 'job_searches', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('is_full_automation', sa.Boolean(), nullable=False),
    sa.Column('ai_model', sa.String(length=50), nullable=False),
    sa.Column('active_boards', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('creativity_level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_subscriptions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.Enum('FREE', 'BASIC', 'PREMIUM', name='clienttype'), nullable=False),
    sa.Column('ai_credits_balance', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_past_due', sa.Boolean(), nullable=False),
    sa.Column('grace_days', sa.Integer(), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancel_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_billing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_subscriptions_stripe_customer_id'), 'user_subscriptions', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_stripe_subscription_id'), 'user_subscriptions', ['stripe_subscription_id'], unique=False)
    op.create_table('job_offers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('search_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('form_url', sa.String(length=500), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('job_title', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('job_board', sa.Enum('WTTJ', 'HELLOWORK', 'APEC', name='jobboard', native_enum=False), nullable=False),
    sa.Column('job_posting_id', sa.String(length=100), nullable=True),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('ranking', sa.Integer(), nullable=True),
    sa.Column('job_desc', sa.Text(), nullable=True),
    sa.Column('application_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('followup_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('FOUND', 'IN_PROGRESS', 'GENERATED', 'APPROVED', 'SUBMITTED', 'FAILED', 'REJECTED', name='applicationstatus', native_enum=False), nullable=False),
    sa.Column('has_interview', sa.Boolean(), nullable=False),
    sa.Column('has_response', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['search_id'], ['job_searches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_offers_company_name'), 'job_offers', ['company_name'], unique=False)
    op.create_index(op.f('ix_job_offers_job_posting_id'), 'job_offers', ['job_posting_id'], unique=False)
    op.create_index(op.f('ix_job_offers_search_id'), 'job_offers', ['search_id'], unique=False)
    op.create_index(op.f('ix_job_offers_url'), 'job_offers', ['url'], unique=False)
    op.create_index(op.f('ix_job_offers_user_id'), 'job_offers', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_offers_user_id'), table_name='job_offers')
    op.drop_index(op.f('ix_job_offers_url'), table_name='job_offers')
    op.drop_index(op.f('ix_job_offers_search_id'), table_name='job_offers')
    op.drop_index(op.f('ix_job_offers_job_posting_id'), table_name='job_offers')
    op.drop_index(op.f('ix_job_offers_company_name'), table_name='job_offers')
    op.drop_table('job_offers')
    op.drop_index(op.f('ix_user_subscriptions_stripe_subscription_id'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_stripe_customer_id'), table_name='user_subscriptions')
    op.drop_table('user_subscriptions')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_job_searches_user_id'), table_name='job_searches')
    op.drop_table('job_searches')
    op.drop_index(op.f('ix_board_credentials_user_id'), table_name='board_credentials')
    op.drop_index(op.f('ix_board_credentials_job_board'), table_name='board_credentials')
    op.drop_table('board_credentials')
    op.drop_index(op.f('ix_auth_users_email'), table_name='auth_users')
    op.drop_table('auth_users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
