"""add resume file name

Revision ID: 81ef9a15ddc3
Revises: 31c54c62cbb0
Create Date: 2026-03-17 01:37:55.958117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81ef9a15ddc3'
down_revision: Union[str, Sequence[str], None] = '31c54c62cbb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('resume_file_name', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'resume_file_name')
    # ### end Alembic commands ###
