"""add_id_columns_to_auth_and_subs

Revision ID: f832cca68c43
Revises: 81ef9a15ddc3
Create Date: 2026-03-17 11:02:24.258213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f832cca68c43'
down_revision: Union[str, Sequence[str], None] = '81ef9a15ddc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_users', sa.Column('id', sa.Uuid(), nullable=True))
    op.add_column('user_preferences', sa.Column('id', sa.Uuid(), nullable=True))
    op.add_column('user_subscriptions', sa.Column('id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_subscriptions', 'id')
    op.drop_column('user_preferences', 'id')
    op.drop_column('auth_users', 'id')
    # ### end Alembic commands ###
